# Generated by Django 5.2.4 on 2025-07-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsupplier',
            name='supplier_price',
        ),
        migrations.RemoveField(
            model_name='productsupplier',
            name='supplier_stock',
        ),
    ]
