# Generated by Django 5.2.4 on 2025-07-28 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productsupplier_supplier_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsuppliers', to='products.product', verbose_name='Producto'),
        ),
    ]
