# Generated by Django 5.2.4 on 2025-07-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productsupplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock',
            field=models.IntegerField(default=50, verbose_name='stock mínimo'),
        ),
    ]
